    /*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 9.0.1   2020-01-19

The MIT License (MIT)
Copyright (c) 2018 STMicroelectronics

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish,  distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

******************************************************************************
*/

/* Includes */

#include "bootloader.h"
#include "stm32f4xx_rcc.h"
#include "stm32f4xx.h"


//buf 32bit word buffer shared between bootloader and application stored in isolated non_init_ram away from memory segments that are set during startup process
//being buf  stored in non_init_memory allows its value to be retained after system/software reset
COMMON_BUF buf;
int main(void)
{
	__enable_irq();//enable interrupts which has been disabled by app before sw reset
	if(APP_START_ADDRESS==FREE_IMAGE||buf==1)//Enter bootloader if no image founds or upgrade request has been  received
	 {
		buf==0;//Reset buffer indicating that the upgrade req has been processed
		boot_process();//enter bootloader
	 }
	else
	{
		jump_to_exist_app((uint32_t)APP_START_ADDRESS);
	}

}
